version: 2

sources:
  - name: erp
    schema: erp_northwind
    description: Fonte de dados de vendas do SAP Northwind
    tables:
      - name: employees
        columns:
          - name: employee_id
            tests:
              - unique
              - not_null
      - name: products
        description: Tabela com os produtos comercializados pela Northwind.
        columns:
          - name: product_id
            tests:
              - unique
              - not_null

      - name: categories
        description: Tabela com as categorias dos produtos comercializados pela Northwind.
        columns:
          - name: category_id
            tests:
              - unique
              - not_null

      - name: suppliers
        description: Tabela de fornecedores dos produtos comercializados pela Northwind.
        columns:
          - name: supplier_id
            tests:
              - unique
              - not_null
      

      